//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentStaff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int IDResTest { get; set; }
        public int UserID { get; set; }
        public int TestID { get; set; }
        public int FirstCountTrueAnswers { get; set; }
        public int LastCountTrueAnswers { get; set; }
        public System.DateTime FirstDateTest { get; set; }
        public System.DateTime LastDateTest { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
